export const BUTTON_COLOR = '#4CD964'
export const INPUT_BORDER = '#EEEEEE'
export const MUTILINE_INPUT_BORDER = '#CCCCCC'
export const HEADER_COLOR = '#4CD964'
export const HEADER_TEXT_COLOR = 'white'
export const BUTTON_ALERT = '#FF3B30'
export const PLACEHOLDER_COLOR = '#9B9B9B'
